State in forms
WildCodeSchool/reims-0919-js-nasa-voyages pull request #8
Opened 2019-11-06 09:31 UTC by Brolyus

Added the user story "Users can add a custom vehicle" to the merged website (from presentation branch). Also, now all the choice from users goes to the state of game.js

2019-11-06 15:47 UTC, rocambille requested changes

2019-11-06 15:47 UTC, wasthishelpful commented on astra/src/components/Game.js
> +      vehicle_options: vehicleList.map(option => option.vehicle),
snake_case à passer en camelCase, un peu partout ;)

2019-11-06 15:55 UTC, ghost requested changes

2019-11-06 15:55 UTC, Sheoo commented on astra/src/components/Game.js
> +      planet_options: planetList.map(option => option.englishName),
use componentDidMount to manage those data

2019-11-06 15:55 UTC, Sheoo commented on astra/src/components/Game.js
> +      console.log(-result);
No need to keep console.log() in dev

2019-11-06 15:55 UTC, Sheoo commented on astra/src/components/Game.js
> +    console.log(vehicleList);
another console log

2019-11-06 15:55 UTC, Sheoo commented on astra/src/components/calculator.js
> +let result = 0
When declaring a function, set all of its value inside it, not outside

2019-11-07 20:00 UTC, Brolyus commented
Fixed in PR 9

2019-11-07 20:00 UTC, closed without merging